import os
import sqlite3
import json
import psycopg2


SQLITE_DB = "attendance.db"


def get_postgres_connection():
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is not set. "
            "Set it to your Render PostgreSQL External Database URL."
        )
    return psycopg2.connect(database_url)


def main():
    if not os.path.exists(SQLITE_DB):
        raise FileNotFoundError(f"{SQLITE_DB} was not found in the current folder.")

    sqlite_conn = sqlite3.connect(SQLITE_DB)
    sqlite_cur = sqlite_conn.cursor()

    sqlite_cur.execute("""
        SELECT id, emp_id, name, department, mobile, face_descriptor
        FROM employees
        ORDER BY id
    """)
    employees = sqlite_cur.fetchall()

    sqlite_cur.execute("""
        SELECT id, emp_id, date, time, status
        FROM attendance
        ORDER BY id
    """)
    attendance = sqlite_cur.fetchall()

    pg_conn = get_postgres_connection()
    pg_cur = pg_conn.cursor()

    # Create the same PostgreSQL tables used by app_postgresql.py.
    pg_cur.execute("""
        CREATE TABLE IF NOT EXISTS employees (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emp_id TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            department TEXT,
            mobile TEXT,
            face_descriptor TEXT
        )
    """)

    pg_cur.execute("""
        CREATE TABLE IF NOT EXISTS attendance (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emp_id TEXT NOT NULL,
            date TEXT NOT NULL,
            time TEXT NOT NULL,
            status TEXT NOT NULL
        )
    """)

    employee_count = 0
    attendance_count = 0

    # Insert/update employees so this script can safely be re-run.
    for row in employees:
        emp_id = row[1]
        face_descriptor = row[5]

        # Older databases may contain a Python-list representation.
        # Convert it to valid JSON when possible.
        if face_descriptor:
            try:
                parsed = json.loads(face_descriptor)
                face_descriptor = json.dumps(parsed)
            except Exception:
                try:
                    import ast
                    parsed = ast.literal_eval(face_descriptor)
                    face_descriptor = json.dumps(list(parsed))
                except Exception:
                    pass

        pg_cur.execute("""
            INSERT INTO employees
                (id, emp_id, name, department, mobile, face_descriptor)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (emp_id) DO UPDATE SET
                name = EXCLUDED.name,
                department = EXCLUDED.department,
                mobile = EXCLUDED.mobile,
                face_descriptor = EXCLUDED.face_descriptor
        """, (row[0], row[1], row[2], row[3], row[4], face_descriptor))
        employee_count += 1

    # Insert attendance only when the same id is not already present.
    for row in attendance:
        pg_cur.execute(
            "SELECT 1 FROM attendance WHERE id = %s",
            (row[0],)
        )
        if pg_cur.fetchone() is None:
            pg_cur.execute("""
                INSERT INTO attendance
                    (id, emp_id, date, time, status)
                VALUES (%s, %s, %s, %s, %s)
            """, row)
            attendance_count += 1

    # Keep identity sequences above the migrated IDs.
    pg_cur.execute("""
        SELECT setval(
            pg_get_serial_sequence('employees', 'id'),
            COALESCE((SELECT MAX(id) FROM employees), 1),
            true
        )
    """)

    pg_cur.execute("""
        SELECT setval(
            pg_get_serial_sequence('attendance', 'id'),
            COALESCE((SELECT MAX(id) FROM attendance), 1),
            true
        )
    """)

    pg_conn.commit()

    pg_cur.close()
    pg_conn.close()
    sqlite_cur.close()
    sqlite_conn.close()

    print("Migration completed successfully.")
    print(f"Employees processed: {employee_count}")
    print(f"New attendance rows inserted: {attendance_count}")


if __name__ == "__main__":
    main()